sudo: false
language: java
os:
  - linux  
env:
  global:
    - PROJECT_NAME=vmbix
    - VERSION=2.1
    - DEPLOY_ROOT=$TRAVIS_BUILD_DIR/deploy-root
    - secure: "pE660u65qVgDijr5lRPSYlogkboLdJw1oSrP8tYLJ9PeHwo6P4vW8UyMCL6PVCrXtPssMpqBlbLR3C57FnRKnD64xWTvjLUbBf7rh/fKqjLYkKVfUIUlDts1HEoHLLo8UzyXNwZp7734eP2dHmyvEgO9MnFRAAD+Ix4ByQwFABfgjvYQI+hk8+eeaJnd5kDQmlfgtT0FTz1P8KwpGVFDWM1Q3HcVLoSDgJNy4CSiofOoMP8TUFhGMaocIroHZMssRsR2SmZ3WG+ob6SLXnzYQZ3T8bt/qZop7uoKF5IXS49RM9a7qk0ARnAPeFmLl0c+qXe35QudWfAh9LHt3c6rDKKHhFcIHQTqLJ5OhhK0zplAtA5LAKckFZ23qw1sxlR1qWaI57GxeZxhZPB1V6iW63WQXS0bV0/c0b25agbGEfqKtmayAMefnonKlwC5kd/AmY+VUow1oEcOru8BmaE2xBPIwBH0v+ojg45gLTB97FcbsUZ7zEnUw82tfKkPENv/NTfjbqMBq21/XIX5uBlr3bSNujhNGZaAsHOWLCZsPgtxlvE118L2UNQlTsa8hYT6LixYJJr+Hai/TEGGS9UbWqSOVjUzXQd+AdMiZqOne9oG5mGgiFgQ2FnYeHI8UY+WWD/ZxJI0vdj2HlB3BOYhGsX6xkY9FJ/+Dxp7T8Gs27I="
  matrix:    
    - TARGET_PLATFORM=deb
    - TARGET_PLATFORM=rpm
addons:
  apt:
    packages:
      - rpm
    sources:
      - ubuntu-toolchain-r-test
install:  
  - mkdir -p ${DEPLOY_ROOT}/usr/local/sbin/
  - mkdir -p ${DEPLOY_ROOT}/usr/local/vmbix/
  - mkdir -p ${DEPLOY_ROOT}/etc
  - gem install fpm
  - export TAR_FILE_NAME=${PROJECT_NAME}-${VERSION}.tar.gz
  - if [ "$TARGET_PLATFORM" == "deb" ]; then export FILE_NAME="${PROJECT_NAME}_${VERSION}-1_amd64"; export JAVA_PACKAGE="default-jre-headless"; fi
  - if [ "$TARGET_PLATFORM" == "rpm" ]; then export FILE_NAME="${PROJECT_NAME}-${VERSION}-1.x86_64"; export JAVA_PACKAGE="java-1.7.0-openjdk-devel"; fi

script:
  - mvn package  
  - cp -dR ${TRAVIS_BUILD_DIR}/target/vmbix-${VERSION}-jar-with-dependencies.jar ${DEPLOY_ROOT}/usr/local/vmbix/vmbix.jar
  - cp -dR ${TRAVIS_BUILD_DIR}/etc-${TARGET_PLATFORM}/* ${DEPLOY_ROOT}/etc/
  - cp -dR ${TRAVIS_BUILD_DIR}/usr/ ${DEPLOY_ROOT}/
  - chmod +x ${DEPLOY_ROOT}/etc/init.d/vmbixd
  - chmod +x ${DEPLOY_ROOT}/usr/local/sbin/vmbix
  - chmod +x ${DEPLOY_ROOT}/usr/local/sbin/vmbixd
  - cd ${DEPLOY_ROOT}/
  - tar -zcf $TRAVIS_BUILD_DIR/$TAR_FILE_NAME .
  - fpm -p $TRAVIS_BUILD_DIR/${FILE_NAME}.${TARGET_PLATFORM} -s dir -t ${TARGET_PLATFORM} -n ${PROJECT_NAME} -v ${VERSION} --iteration 1 -C ${DEPLOY_ROOT} --description "${PROJECT_NAME} ${VERSION}" -d "${JAVA_PACKAGE}" usr etc

after_success:
  - curl -T $TRAVIS_BUILD_DIR/${TAR_FILE_NAME} -ukireevco:${BINTRAY_KEY} https://api.bintray.com/content/kireevco/generic/${PROJECT_NAME}/${VERSION}/${TAR_FILE_NAME}
  - curl -T $TRAVIS_BUILD_DIR/${FILE_NAME}.${TARGET_PLATFORM} -ukireevco:${BINTRAY_KEY} https://api.bintray.com/content/kireevco/${TARGET_PLATFORM}/${PROJECT_NAME}/${VERSION}/${FILE_NAME}.${TARGET_PLATFORM}
